module.exports = {
  "data": [{
    "ProductID": 5896336,
    "Url": "/morelinetravel/p5896336s1.html",
    "EffectDate": "2016-05-05",
    "ExpireDate": "2016-07-13",
    "Name": "美国东海岸+西海岸+纽约+拉斯维加斯15日跟团游(3钻)·MU夏威夷+环球影城+B线增游名校+特卖汇",
    "PicUrl": "http://dimg04.c-ctrip.com/images/vacations/images2/66/250/250_17_C_190_106.jpg",
    "MarketingTag": null,
    "ProductDepartureCity": "北京",
    "ProductDepartureCityID": 1,
    "OtherDepartureCities": [{
      "Name": "上海",
      "ID": 2
    }, {
      "Name": "天津",
      "ID": 3
    }, {
      "Name": "重庆",
      "ID": 4
    }, {
      "Name": "哈尔滨",
      "ID": 5
    }, {
      "Name": "大连",
      "ID": 6
    }, {
      "Name": "青岛",
      "ID": 7
    }, {
      "Name": "西安",
      "ID": 10
    }, {
      "Name": "南京",
      "ID": 12
    }, {
      "Name": "无锡",
      "ID": 13
    }, {
      "Name": "苏州",
      "ID": 14
    }, {
      "Name": "扬州",
      "ID": 15
    }, {
      "Name": "厦门",
      "ID": 25
    }, {
      "Name": "成都",
      "ID": 28
    }, {
      "Name": "深圳",
      "ID": 30
    }, {
      "Name": "珠海",
      "ID": 31
    }, {
      "Name": "广州",
      "ID": 32
    }, {
      "Name": "桂林",
      "ID": 33
    }, {
      "Name": "昆明",
      "ID": 34
    }, {
      "Name": "丽江",
      "ID": 37
    }, {
      "Name": "贵阳",
      "ID": 38
    }, {
      "Name": "乌鲁木齐",
      "ID": 39
    }, {
      "Name": "拉萨",
      "ID": 41
    }, {
      "Name": "三亚",
      "ID": 43
    }, {
      "Name": "南通",
      "ID": 82
    }, {
      "Name": "银川",
      "ID": 99
    }, {
      "Name": "兰州",
      "ID": 100
    }, {
      "Name": "呼和浩特",
      "ID": 103
    }, {
      "Name": "太原",
      "ID": 105
    }, {
      "Name": "喀什市",
      "ID": 109
    }, {
      "Name": "西宁",
      "ID": 124
    }, {
      "Name": "运城",
      "ID": 140
    }, {
      "Name": "包头",
      "ID": 141
    }, {
      "Name": "海拉尔",
      "ID": 142
    }, {
      "Name": "济南",
      "ID": 144
    }, {
      "Name": "长春",
      "ID": 158
    }, {
      "Name": "长沙",
      "ID": 206
    }, {
      "Name": "常州",
      "ID": 213
    }, {
      "Name": "佛山",
      "ID": 251
    }, {
      "Name": "福州",
      "ID": 258
    }, {
      "Name": "合肥",
      "ID": 278
    }, {
      "Name": "连云港",
      "ID": 353
    }, {
      "Name": "绵阳",
      "ID": 370
    }, {
      "Name": "南昌",
      "ID": 376
    }, {
      "Name": "南宁",
      "ID": 380
    }, {
      "Name": "石家庄",
      "ID": 428
    }, {
      "Name": "沈阳",
      "ID": 451
    }, {
      "Name": "武汉",
      "ID": 477
    }, {
      "Name": "威海",
      "ID": 479
    }, {
      "Name": "温州",
      "ID": 491
    }, {
      "Name": "西昌",
      "ID": 494
    }, {
      "Name": "徐州",
      "ID": 512
    }, {
      "Name": "延吉",
      "ID": 523
    }, {
      "Name": "榆林",
      "ID": 527
    }, {
      "Name": "烟台",
      "ID": 533
    }, {
      "Name": "义乌",
      "ID": 536
    }, {
      "Name": "郑州",
      "ID": 559
    }, {
      "Name": "台州",
      "ID": 578
    }],
    "MinPrice": 16399.0,
    "MinPriceRemark": "1、本起价是按2位成人参加2016-06-04出发的团队所核算的<strong style='color:red'>单人价格</strong>。<br/>2、此最低价格已包含以下内容：<br>1)15日游套餐<br>2)东航联运1线<br>3、您最终提交的价格会根据您所选择的出发日期、出行人数以及所选附加服务的不同而有所差别。",
    "DepartureDays": "06/04,06/29",
    "RecommendRatings": "0.0",
    "CommentUsers": 0,
    "Days": 15,
    "EveryDayCost": 1093.2666666666666666666666667,
    "Transportation": "飞机",
    "DiscountInfos": [{
      "DisplayName": "特卖汇",
      "Description": null
    }],
    "ProductRecommends": [{
      "DescDetail": "美国全景冲量不赚钱,丰富团期,包含好莱坞影城+游船+旧金山+夏威夷哦！",
      "URL": null
    }, {
      "DescDetail": "东航直飞，支持全国联运， 国际段免费托运两件行李！",
      "URL": null
    }, {
      "DescDetail": "B线增游美国顶尖名校:哥伦比亚+普林斯顿+柏克莱+UCLA+哈佛+麻省！",
      "URL": null
    }],
    "TourFlightsInfo": [{
      "OrderDay": 1,
      "Flights": [{
        "Description": "MU571  PVGHNL 1620 0810",
        "DriveTime": "8小时"
      }]
    }],
    "TourHotelsInfo": [{
      "OrderDay": 1,
      "Hotels": [{
        "Name": "当地经济型酒店1",
        "HotelID": 0,
        "URL": ""
      },{
        "Name": "当地经济型酒店1",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 3,
      "Hotels": [{
        "Name": "当地经济型酒店3",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 4,
      "Hotels": [{
        "Name": "当地经济型酒店4",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 6,
      "Hotels": [{
        "Name": "当地经济型酒店6",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 12,
      "Hotels": [{
        "Name": "当地经济型酒店12",
        "HotelID": 0,
        "URL": ""
      }]
    }],
    "TourScenicsInfo": [{
      "OrderDay": 1,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/honolulu2060/66217.html",
        "Name": "珍珠港",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/hawaii251/138717.html",
        "Name": "夏威夷州长官邸（华盛顿宫）",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/honolulu2060/137437.html",
        "Name": "卡美哈美哈国王铜像",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 2,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/honolulu2060/66215.html",
        "Name": "恐龙湾",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/honolulu2060/66498.html",
        "Name": "大风口",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 4,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/sanfrancisco249/26999.html",
        "Name": "渔人码头",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/sanfrancisco249/13601.html",
        "Name": "旧金山市政厅",
        "OrFlag": true
      }, {
        "URL": "http://you.ctrip.com/sight/sanfrancisco249/27015.html",
        "Name": "九曲花街",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/sanfrancisco249/13621.html",
        "Name": "金门大桥",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 5,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/losangeles250/55274.html",
        "Name": "好莱坞星光大道",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/losangeles250/107459.html",
        "Name": "TCL中国剧院",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/losangeles250/55501.html",
        "Name": "好莱坞环球影城",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 7,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/losangeles250/1815366.html",
        "Name": "洛杉矶音乐中心",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/shopping/barstow18208/1447768.html",
        "Name": "巴斯托奥特莱斯",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 10,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/niagarafalls1527/1786920.html",
        "Name": "尼亚加拉瀑布",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 11,
      "Scenics": [{
        "URL": "http://you.ctrip.com/resort/washingtondc257/1492535.html",
        "Name": "华盛顿特区国会大厦+白宫+林肯纪念馆一日游",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/washingtondc257/13526.html",
        "Name": "华盛顿纪念碑",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/washingtondc257/13557.html",
        "Name": "林肯纪念堂",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/washingtondc257/13556.html",
        "Name": "美国国会大厦",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 12,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/newyork248/13592.html",
        "Name": "自由女神像",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/newyork248/13598.html",
        "Name": "华尔街",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/newyork248/67616.html",
        "Name": "洛克菲勒中心",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/shopping/newyork248/52186.html",
        "Name": "第五大道",
        "OrFlag": false
      }]
    }],
    "TourDinnersInfo": {
      "TourDinnersInfo": [{
        "OrderDay": 1,
        "BreakFast": "自理",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 2,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 3,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 4,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "自理",
        "Meals": null
      }, {
        "OrderDay": 5,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 6,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "自理",
        "Meals": null
      }, {
        "OrderDay": 7,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 8,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "自理",
        "Meals": null
      }, {
        "OrderDay": 9,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "自理",
        "Meals": null
      }, {
        "OrderDay": 10,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 11,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 12,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 13,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "自理",
        "Meals": null
      }, {
        "OrderDay": 14,
        "BreakFast": null,
        "Lunch": null,
        "Supper": null,
        "Meals": null
      }, {
        "OrderDay": 15,
        "BreakFast": null,
        "Lunch": null,
        "Supper": null,
        "Meals": null
      }]
    },
    "TourShoppingInfo": {
      "ShopTimes": 4,
      "Shoppings": [{
        "Scenics": [{
          "URL": null,
          "Name": "PUPU OUTLET",
          "OrFlag": false
        }],
        "ProductsOnSale": "主要经营土产等"
      }, {
        "Scenics": [{
          "URL": null,
          "Name": "Van Less gift outlets",
          "OrFlag": false
        }],
        "ProductsOnSale": "主要经营各色有色宝石，钻石、工艺品，土产等"
      }, {
        "Scenics": [{
          "URL": null,
          "Name": "Van Less gift outlets",
          "OrFlag": false
        }],
        "ProductsOnSale": "主要经营各色有色宝石，钻石、工艺品，土产等"
      }, {
        "Scenics": [{
          "URL": null,
          "Name": "丰源礼品店",
          "OrFlag": false
        }],
        "ProductsOnSale": "主要经营各色有色宝石，钻石、工艺品，土产等"
      }]
    },
    "TourSelfChargeActivitiesInfo": {
      "ActivityTimes": 0,
      "SelfChargeActivities": []
    },
    "FeeInfos": [],
    "ProviderName": "明游北美",
    "ProductSummary": {
      "HasProductSummary": true,
      "HotelStarInfo": "暂无酒店信息",
      "SightInfo": "共23个景点，包含11个经典景点",
      "ClassicSightInfo": null,
      "FlightFlyInfo": "飞行时长8小时<span class=\"abc_fly_nostop\">直飞</span>",
      "SelfCareInfo": "27次非自理，12次自理",
      "FreeActiveInfo": "暂无自由活动信息",
      "DriveTimeInfo": "行车时长2小时",
      "CharacteristicTeamDinner": null
    }
  }, {
    "ProductID": 5890762,
    "Url": "/morelinetravel/p5890762s1.html",
    "EffectDate": "2016-05-09",
    "ExpireDate": "2016-07-16",
    "Name": "美国东西海岸+黄石国家公园+尼亚加拉大瀑布18日跟团游(3钻)·夏威夷+环球影城+大瀑布+暑假游名校+特卖汇",
    "PicUrl": "http://dimg04.c-ctrip.com/images/vacations/images2/66/248/248_96_s35083_C_190_106.jpg",
    "MarketingTag": null,
    "ProductDepartureCity": "北京",
    "ProductDepartureCityID": 1,
    "OtherDepartureCities": [{
      "Name": "上海",
      "ID": 2
    }, {
      "Name": "天津",
      "ID": 3
    }, {
      "Name": "重庆",
      "ID": 4
    }, {
      "Name": "哈尔滨",
      "ID": 5
    }, {
      "Name": "大连",
      "ID": 6
    }, {
      "Name": "青岛",
      "ID": 7
    }, {
      "Name": "西安",
      "ID": 10
    }, {
      "Name": "南京",
      "ID": 12
    }, {
      "Name": "无锡",
      "ID": 13
    }, {
      "Name": "苏州",
      "ID": 14
    }, {
      "Name": "扬州",
      "ID": 15
    }, {
      "Name": "杭州",
      "ID": 17
    }, {
      "Name": "黄山",
      "ID": 23
    }, {
      "Name": "厦门",
      "ID": 25
    }, {
      "Name": "成都",
      "ID": 28
    }, {
      "Name": "珠海",
      "ID": 31
    }, {
      "Name": "广州",
      "ID": 32
    }, {
      "Name": "桂林",
      "ID": 33
    }, {
      "Name": "昆明",
      "ID": 34
    }, {
      "Name": "贵阳",
      "ID": 38
    }, {
      "Name": "乌鲁木齐",
      "ID": 39
    }, {
      "Name": "拉萨",
      "ID": 41
    }, {
      "Name": "海口",
      "ID": 42
    }, {
      "Name": "三亚",
      "ID": 43
    }, {
      "Name": "南通",
      "ID": 82
    }, {
      "Name": "银川",
      "ID": 99
    }, {
      "Name": "兰州",
      "ID": 100
    }, {
      "Name": "呼和浩特",
      "ID": 103
    }, {
      "Name": "太原",
      "ID": 105
    }, {
      "Name": "西宁",
      "ID": 124
    }, {
      "Name": "包头",
      "ID": 141
    }, {
      "Name": "海拉尔",
      "ID": 142
    }, {
      "Name": "济南",
      "ID": 144
    }, {
      "Name": "长春",
      "ID": 158
    }, {
      "Name": "长沙",
      "ID": 206
    }, {
      "Name": "常州",
      "ID": 213
    }, {
      "Name": "佛山",
      "ID": 251
    }, {
      "Name": "福州",
      "ID": 258
    }, {
      "Name": "合肥",
      "ID": 278
    }, {
      "Name": "宁波",
      "ID": 375
    }, {
      "Name": "南昌",
      "ID": 376
    }, {
      "Name": "南宁",
      "ID": 380
    }, {
      "Name": "石家庄",
      "ID": 428
    }, {
      "Name": "沈阳",
      "ID": 451
    }, {
      "Name": "武汉",
      "ID": 477
    }, {
      "Name": "威海",
      "ID": 479
    }, {
      "Name": "温州",
      "ID": 491
    }, {
      "Name": "西昌",
      "ID": 494
    }, {
      "Name": "徐州",
      "ID": 512
    }, {
      "Name": "宜昌",
      "ID": 515
    }, {
      "Name": "延吉",
      "ID": 523
    }, {
      "Name": "烟台",
      "ID": 533
    }, {
      "Name": "郑州",
      "ID": 559
    }, {
      "Name": "台州",
      "ID": 578
    }],
    "MinPrice": 21900.0,
    "MinPriceRemark": "1、本起价是按2位成人参加2016-06-17出发的团队所核算的<strong style='color:red'>单人价格</strong>。<br/>2、此最低价格已包含以下内容：<br>1)18日游套餐<br>2)东航联运100<br>3、您最终提交的价格会根据您所选择的出发日期、出行人数以及所选附加服务的不同而有所差别。",
    "DepartureDays": "周二,三,四,五",
    "RecommendRatings": "0.0",
    "CommentUsers": 0,
    "Days": 18,
    "EveryDayCost": 1216.6666666666666666666666667,
    "Transportation": "飞机",
    "DiscountInfos": [{
      "DisplayName": "特卖汇",
      "Description": null
    }],
    "ProductRecommends": [{
      "DescDetail": "超高性价比!C线暑假团期增游4大名校!黄石+好莱坞影城+游船+夏威夷！",
      "URL": null
    }, {
      "DescDetail": "包含景点门票：环球影城、自由女神游船、黄石公园！",
      "URL": null
    }, {
      "DescDetail": "特别赠送:巴士通奥特莱斯,满足您的购物需求!丰富班期提前预售！",
      "URL": null
    }],
    "TourFlightsInfo": [{
      "OrderDay": 1,
      "Flights": [{
        "Description": "MU297    PVGJFK  1930 2215",
        "DriveTime": "15小时"
      }]
    }],
    "TourHotelsInfo": [{
      "OrderDay": 2,
      "Hotels": [{
        "Name": "当地经济型酒店2",
        "HotelID": 0,
        "URL": "http://www.ctrip.com/"
      }]
    }, {
      "OrderDay": 4,
      "Hotels": [{
        "Name": "当地经济型酒店4",
        "HotelID": 0,
        "URL": "http://vacations.ctrip.com/"
      }]
    }, {
      "OrderDay": 5,
      "Hotels": [{
        "Name": "当地经济型酒店5",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 6,
      "Hotels": [{
        "Name": "当地经济型酒店",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 7,
      "Hotels": [{
        "Name": "当地经济型酒店",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 11,
      "Hotels": [{
        "Name": "当地经济型酒店",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 12,
      "Hotels": [{
        "Name": "当地经济型酒店",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 13,
      "Hotels": [{
        "Name": "当地经济型酒店",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 14,
      "Hotels": [{
        "Name": "当地经济型酒店",
        "HotelID": 0,
        "URL": ""
      }]
    }, {
      "OrderDay": 15,
      "Hotels": [{
        "Name": "当地经济型酒店",
        "HotelID": 0,
        "URL": ""
      }]
    }],
    "TourScenicsInfo": [{
      "OrderDay": 2,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/newyork248/13598.html",
        "Name": "华尔街",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/newyork248/13603.html",
        "Name": "联合国总部",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/newyork248/13592.html",
        "Name": "自由女神像",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/newyork248/67616.html",
        "Name": "洛克菲勒中心",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 3,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/washingtondc257/13564.html",
        "Name": "美国白宫",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/washingtondc257/107536.html",
        "Name": "越战纪念碑",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/washingtondc257/13526.html",
        "Name": "华盛顿纪念碑",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/washingtondc257/13557.html",
        "Name": "林肯纪念堂",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 4,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/niagarafalls1527/1786920.html",
        "Name": "尼亚加拉瀑布",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 6,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/sanfrancisco249/13621.html",
        "Name": "金门大桥",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/sanfrancisco249/13596.html",
        "Name": "旧金山唐人街",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/sanfrancisco249/27015.html",
        "Name": "九曲花街",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/sanfrancisco249/26999.html",
        "Name": "渔人码头",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 7,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/idahofalls39994/1408871.html",
        "Name": "爱达荷人工瀑布",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 8,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/yellowstonenationalpark120415/75895.html",
        "Name": "黄石国家公园",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/yellowstonenationalpark120415/133234.html",
        "Name": "黄石湖",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/yellowstonenationalpark120415/133227.html",
        "Name": "老忠实间歇泉",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 12,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/losangeles250/1815366.html",
        "Name": "洛杉矶音乐中心",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/losangeles250/138651.html",
        "Name": "斯台普斯中心",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 13,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/losangeles250/55274.html",
        "Name": "好莱坞星光大道",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/losangeles250/109916.html",
        "Name": "杜比剧院",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/losangeles250/55501.html",
        "Name": "好莱坞环球影城",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 15,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/honolulu2060/66217.html",
        "Name": "珍珠港",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/honolulu2060/137437.html",
        "Name": "卡美哈美哈国王铜像",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/honolulu2060/1691205.html",
        "Name": "夏威夷州议会大厦",
        "OrFlag": false
      }]
    }, {
      "OrderDay": 16,
      "Scenics": [{
        "URL": "http://you.ctrip.com/sight/honolulu2060/66498.html",
        "Name": "大风口",
        "OrFlag": false
      }, {
        "URL": "http://you.ctrip.com/sight/honolulu2060/66215.html",
        "Name": "恐龙湾",
        "OrFlag": false
      }]
    }],
    "TourDinnersInfo": {
      "TourDinnersInfo": [{
        "OrderDay": 1,
        "BreakFast": "自理",
        "Lunch": "自理",
        "Supper": "自理",
        "Meals": null
      }, {
        "OrderDay": 2,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 4,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 5,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "自理",
        "Meals": null
      }, {
        "OrderDay": 6,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 7,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 8,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 9,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 10,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 11,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "自理",
        "Meals": null
      }, {
        "OrderDay": 12,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 13,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 14,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "自理",
        "Meals": null
      }, {
        "OrderDay": 15,
        "BreakFast": "酒店内早餐",
        "Lunch": "自理",
        "Supper": "中式团餐",
        "Meals": null
      }, {
        "OrderDay": 16,
        "BreakFast": "酒店内早餐",
        "Lunch": "中式团餐",
        "Supper": "自理",
        "Meals": null
      }, {
        "OrderDay": 17,
        "BreakFast": null,
        "Lunch": null,
        "Supper": null,
        "Meals": null
      }, {
        "OrderDay": 18,
        "BreakFast": null,
        "Lunch": null,
        "Supper": null,
        "Meals": null
      }]
    },
    "TourShoppingInfo": {
      "ShopTimes": 4,
      "Shoppings": [{
        "Scenics": [{
          "URL": null,
          "Name": "美国礼品店",
          "OrFlag": false
        }],
        "ProductsOnSale": "主要经营各色有色宝石，钻石、工艺品，土产等"
      }, {
        "Scenics": [{
          "URL": null,
          "Name": "旧金山礼品店",
          "OrFlag": false
        }],
        "ProductsOnSale": "主要经营各色有色宝石，钻石、工艺品，土产等"
      }, {
        "Scenics": [{
          "URL": null,
          "Name": "丰源礼品店",
          "OrFlag": false
        }],
        "ProductsOnSale": "主要经营各色有色宝石，钻石、工艺品，土产等"
      }, {
        "Scenics": [{
          "URL": null,
          "Name": "夏威夷土特产店",
          "OrFlag": false
        }],
        "ProductsOnSale": "主要经营土产等"
      }]
    },
    "TourSelfChargeActivitiesInfo": {
      "ActivityTimes": 0,
      "SelfChargeActivities": []
    },
    "FeeInfos": [],
    "ProviderName": "明游北美",
    "ProductSummary": {
      "HasProductSummary": true,
      "HotelStarInfo": "暂无酒店信息",
      "SightInfo": "共27个景点，包含15个经典景点",
      "ClassicSightInfo": null,
      "FlightFlyInfo": "飞行时长15小时<span class=\"abc_fly_nostop\">直飞</span>",
      "SelfCareInfo": "32次非自理，16次自理",
      "FreeActiveInfo": "暂无自由活动信息",
      "DriveTimeInfo": "行车时长8.2小时",
      "CharacteristicTeamDinner": null
    }
  }],
  "errno": 0,
  "errmsg": "OK"
}