module.exports = {
  "data": {
    "Pkg": 6673978,
    "FeeInfos": [{
      "TitleName": "费用包含",
      "PkgDescEntitys": [{
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "费用包含",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "往返经济舱机票、燃油附加费（以实际收费标准为准）、",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "费用包含",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "行程所列酒店住宿费用",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "费用包含",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "酒店标准2人间",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "费用包含",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "酒店最多可容纳4人包括小孩；一般酒店房间内备有一张或两张床，当三人一房或四人一房时，得使用现有床位，不另加床；若加床，其费用由旅客自行承担，并自行与酒店协商。",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "费用包含",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "全程三餐自理",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "费用包含",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "当地专业中英文双语导览（需额外支付小费8美金/人/天）",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "费用包含",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "空调舒适有保险的巴士。",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "费用包含",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "行程中所列景点首道大门票，纳帕谷，17哩湾，黄石公园，大提顿公园，布莱斯峡谷，东南双峡！",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "费用包含",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "年龄3--12周岁（不含）,不占床,服务标准同成人",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }]
    }, {
      "TitleName": "自理费用",
      "PkgDescEntitys": [{
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "自理费用",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "本产品不包含美国签证费用，如需代办请支付1200元/人。",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "自理费用",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "出入境个人物品海关征税，超重行李的托运费、保管费。",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "自理费用",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "因交通延阻、罢工、天气、飞机、机器故障、航班取消或更改时间等不可抗力原因所导致的额外费用。",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "自理费用",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "酒店内洗衣、理发、电话、传真、收费电视、饮品、烟酒等个人消费。",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "自理费用",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "以上“费用包含”中不包含的其它项目。",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "自理费用",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "单房差",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "自理费用",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "不包括接机服务费：$4.00/人<br>不包括提供给导游和司机的服务费（每位客人支付司机及导游服务费：共$8.00/每天）<br>所有个人费用和饮食，行程中的门票或自费项目(价格会因为季节变化而有所调整，最终请以当地公园门市价格为标准)。<br>自费项目表<br> 大人<br> 儿童<br> <br>拉斯维加斯夜游 las vegas night tour<br> $35.00<br> （占位同价）<br> <br>拉斯维加斯大型歌舞表演（限18岁以上）<br> $93.00/$115vip<br> *<br> <br>大卫魔术秀 david copperfield magic<br> $160.00<br> $160（需5岁以上）<br> <br>拉斯维加斯魔术表演 las vegas magic show<br>    $98.00<br> $98（需5岁以上）<br> <br>世界第一秀-水之梦 le reve / the dream<br> $160.00<br> $160（需6岁以上）<br> <br>太阳剧团欧秀”o” by cirque du soleil<br> $230.00<br> $230（需5岁以上）<br> <br>太阳剧团奇异剧场 zarkana – cirque du soleil<br> $119.00<br> $119（需5岁以上）<br> <br>杜莎夫人蜡像馆 madame tussauds hollywood<br> $25.00<br> $20.00（4-12岁）<br> <br>赫氏古堡 hearst castle<br> $25.00<br> $12.00<br> <br>旧金山游船90分钟 san francisco bay cruise<br> $38.00<br> $26.00（5-12岁）<br> <br>旧金山游船60分钟 san francisco bay cruise<br> $30.00<br> $20.00（5-12岁）<br> <br>旧金山深度游s.f.optional tour<br> $35.00<br> （占位同价）<br> <br>17哩门票+优胜美地门票+斯坦福大学停车费(必付项目)<br>    $15.00<br> （占位同价）<br> <br>大峡谷国家公园门票 ground national park admission<br> $25<br> （占位同价）<br> <br>南峡谷直升机 south rim gcn helicopter<br>   $233.00<br> （2岁以上同价）<br> <br>南峡谷双飞小飞机air & ground tour south rim gcn<br>    $364.00<br> $344（2-11岁）<br> <br>南峡谷单飞小飞机air only tour south rim gcn<br>    $189.00<br> （2岁以上同价）<br> <br>棕榈泉直销中心一日游 desert hills premium outlets<br> $60.00<br> $55（3-9岁）<br> <br>包伟湖游船 lake powell cruise<br> $50.00<br> $40（5-10岁）<br> <br>蒙特利水族馆 monterey bay aquarium<br>    $40.00<br> $25.00（3-12岁）<br> <br>红木森林小火车train thru the redwoods<br>    $29.00<br> $23.00（2-12岁）<br> <br>海湾游轮<br>    $25.00<br> $18（5-17岁）<br> <br>拉斯维加斯的美味中式海鲜自助餐<br> $9.99<br> $6.99（5-10 岁）<br> <br>导游,司机每位每天（必付）小费 driver & tour guide tips<br>    $8.00<br>   $8.00<br> <br>备注：<br><br>南峡谷直升机与西峡谷直升机不同，它没有下到峡谷底部，只在峡谷间飞行。<br><br>价格如有变动恕不另行通知。<br> <br> <br>",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "费用",
        "SubTitle": "自理费用",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "餐食：本产品为境外当地参团产品，全程不含餐，敬请自理。",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }]
    }],
    "SelfFeeInfos": null,
    "VisaInfo": {
      "VisaNote": "签证须知",
      "VisaContainDetails": [{
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "签证/签注",
        "SubTitle": "签证须知",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "需旅行社代办美国签证的客人：a. 本产品仅适用于持中国大陆颁发的因私护照的公民签证代办，此范围以外人士的签证请自理，并在签证有效期内使用。b. 如果您需要签证服务，我公司将在产品确认后的72小时内通知您收取签证材料，如距离产品报名截止日期不足72小时，以报名截止日期为准。逾期未交材料我们将取消订单。c. 收到签证材料后，签证即开始受理操作，届时如您取消签证服务，无法退款。d. 请于出发前一个月递交预约面试的材料（预约美国签证面谈所需资料：签证申请表、护照首页复印件、身份证正反面复印件、美国签证照片电子版）。e. 如面试后签证状态为“行政审理”（administrative processing），请第一时间联系携程，我们建议您先取消行程，订单中已产生损失部分需要您自行承担，如果您选择继续等待，损失可能会增加。（行政审理我司无法与领馆协调，如需增补材料在行政审理单上会有说明或者领馆会做相应通知。大多数行政审理程序会在签证面谈结束后30-60天内完成，但也可能早于30天或晚于60天，具体审核时间将视各申请案例的具体情况而定，客人需随时关注自己的签证进度。）f. 若您已经获得美国签证，或在等待面试时，此行程因故宣布取消：由于美国商务及旅游签证（b1/b2签证）有效期为一年，有效期内可多次进出美国。持有此类签证，您可以自由指定您的旅游计划，单独或者跟随任意团队前往。因此签证费用恕不退还。",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "签证/签注",
        "SubTitle": "签证须知",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "1）携程独家拒签保障：如预订本产品同时选择美国签证选项，一旦拒签，签证费不退（签证费已被领馆收取），被拒签人的其他费用将按我司特殊原因退订保障的方式退回。请在被拒签后的两个工作日内一并提供美国领馆拒签说明信，否则无法享受此优惠政策。\n2）我公司将在产品确认后的72小时内通知您收取签证材料，如距离产品报名截止日期不足72小时，以报名截止日期为准。逾期未交材料我们将取消订单。\n收到签证材料后，签证即开始受理操作，届时如您取消签证服务，无法退款。\n",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }, {
        "Pkg": 6673978,
        "Sequence": 0,
        "MainTitle": "签证/签注",
        "SubTitle": "签证须知",
        "Symbol": null,
        "DetailSequence": 0,
        "Detail": "自备签证旅客说明：a.请提供护照首页复印件、签证页复印件，以备使/领馆或航空公司抽查。请确认您的护照有效期自预计回国日期起必须有6个月以上的有效期。出境时航空公司将进行检查，若有效期不足，航空公司会拒绝您登机。 b.如您持外籍护照前往中国境外，请确保持有再次进入中国大陆的有效签证。c.如因自备签证问题造成行程受阻，相应损失需自行承担。   ",
        "Style": null,
        "Color": "",
        "ClauseTypeName": null
      }],
      "AgencyNote": "签证代办须知",
      "AgencyContainDetail": "如果您需要我公司为您代办本产品的签证，收取材料的截止日期如下：<br />05-15 出发团队，04-11 下午17：30截止收取材料；<br />05-16 出发团队，04-11 下午17：30截止收取材料；<br />05-22 出发团队，04-18 下午17：30截止收取材料；<br />05-24 出发团队，04-19 下午17：30截止收取材料；<br />05-29 出发团队，04-25 下午17：30截止收取材料；<br />05-30 出发团队，04-25 下午17：30截止收取材料；<br />06-06 出发团队，05-04 下午17：30截止收取材料；<br />06-15 出发团队，05-12 下午17：30截止收取材料；<br />06-16 出发团队，05-13 下午17：30截止收取材料；<br />06-19 出发团队，05-17 下午17：30截止收取材料；<br />06-28 出发团队，05-25 下午17：30截止收取材料；<br />07-05 出发团队，06-01 下午17：30截止收取材料；<br />08-28 出发团队，07-26 下午17：30截止收取材料；<br />09-05 出发团队，08-02 下午17：30截止收取材料；<br />09-07 出发团队，08-04 下午17：30截止收取材料；<br />09-09 出发团队，08-08 下午17：30截止收取材料；<br />09-12 出发团队，08-09 下午17：30截止收取材料；<br />09-14 出发团队，08-11 下午17：30截止收取材料；<br />09-16 出发团队，08-12 下午17：30截止收取材料；<br />09-19 出发团队，08-15 下午17：30截止收取材料；<br />10-03 出发团队，08-29 下午17：30截止收取材料；<br />10-04 出发团队，08-29 下午17：30截止收取材料；<br />10-05 出发团队，08-29 下午17：30截止收取材料；<br />",
      "VisaHeadNote": "请根据自身情况选择签证所需材料&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;★为必须提供的材料&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;●为根据个人情况酌情提供",
      "VisaCountryInfos": [{
        "Country": "美国",
        "VisaID": 2579,
        "Name": "美国个人旅游签证（需面试，团队/自由行/半自助使用）",
        "ResourceID": 6673980,
        "ResourceName": "美国个人旅游签证（需面试，团队/自由行/半自助使用）",
        "VisaType": "1",
        "VisaRang": "10年（以领馆签发为准）",
        "VisaWorktime": "收齐材料后需14个工作日",
        "VisaManageCity": "上海",
        "VisaAcceptedRange": "全国签发的护照。",
        "VisaAcceptability": null,
        "VisaUnAcceptability": null,
        "VisaRemark": "1、面谈当天需携带护照原件、我司配送给您的所有材料（护照复印件、照片、DS160确认单、预约信），以及其他<a href=http://pages.ctrip.com/tour/visa/ingroup1306/41.htm target=_blank>支持性文件</a>（不提供支持性文件不会影响送签，但如果领馆抽查时无法提供，则可能影响签证结果）按时前往领馆进行面谈。请勿折叠、涂改打印出来的DS-160确认页；<br><br>2、面谈当天按领馆要求排队（具体咨询领馆工作人员），领馆将不允许晚于预约时间半小时以上的申请人进入签证处面试（我司不设面试陪同人员）；<br><br>3、80周岁及以上者或14周岁以下儿童，如从未被拒签过，本人无需前往领馆面试，可通过中信银行的签证“代传递”程序申请签证。如14周岁以下儿童的父母一方或双方需前往领馆申请同一类型的签证，儿童的材料可由其带至领馆一并递交，但需提供父/母的身份证复印件及儿童的出生证明原件（一名成年申请人如携带超过5名儿童材料，则儿童签证必须通过代传递服务进行申请）；<br><br>4、14周岁以下儿童如与父母外的其他亲属同行，则儿童签证必须通过代传递服务申请签证。",
        "SignPlace": "上海",
        "VisaClientTypes": [{
          "ID": 1,
          "Name": "在职",
          "VisaStuffs": [{
            "ID": 27111,
            "Name": "中国大陆因私护照复印件（可接收电子护照）",
            "Content": "1、护照的首页、延期页、换发页复印件；<br>\n2、行程结束后至少还有6个月有效期；<br>\n3、如若换发过护照，提供旧护整本复印件。若无或遗失，则无需提供；<br>\n4、至少留有1页空白签证页，不含备注页；<br>\n5、护照须有中文签名，学龄前儿童可由父母代签名（不可用铅笔）；<br> \n6、不接收6个月内有美国拒签记录的护照。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 1,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27110,
            "Name": "照片（1张）",
            "Content": "1、近6个月内的（5.1cmx5.1cm）白底彩照1张（照片背后用铅笔写姓名）；<br> 2、须包含整个面部，颈部和肩膀；如佩戴眼镜，不得出现反光；<br> 3、不得经过数码处理，增强效应，修版，颗粒化，压缩引起的任何可视效果。 <a href=http://pages.ctrip.com/tour/ingroup1311/074.htm target=_blank> 照片规格参考</a> ",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 2,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27109,
            "Name": "个人信息表",
            "Content": "1、填写完整并中文签名，儿童可由父母代签名；<a href=http://pages.ctrip.com/tour/visa/word/171.doc target=_blank>个人信息表 </a> <a href=http://pages.ctrip.com/tour/ingroupline_pages.asp?folder=ingroup1211&file=102 target=_blank>个人信息表填写样图 </a><br> 2、填写的联系电话需保持畅通。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 3,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27113,
            "Name": "英文邀请函复印件（仅出行目的为商务的客人提供）",
            "Content": "1、美国公司邀请函复印件，使用抬头纸打印，签字并盖章； <br>\n（1）抬头包括：公司名称、地址、电话、传真等信息；<br>\n（2）邀请函内容包括：被邀请人信息（姓名、护照号码、职务）、被邀请人公司信息（名称、地址、电话、传真）、访问目的、逗留期限、日程安排、费用支付方（旅费及医疗保险）、邀请方担保申请人按时回国、邀请公司的联系人、签字人的姓名和职务。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 5,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27112,
            "Name": "备注",
            "Content": "当符合下列条件时，持因私护照签证申请人可选择我司美国个人旅游签证，中信银行“代传递”免面试产品。<br> 1、申请人上一次赴美签证过期时间不超过48个月，此次申请签证类型与上次相同，有过期的美国签证页所在的护照（如护照为因公护照，需包含清晰的出入境四个章），您必须在之前的签证面试时提供过十指指纹，未被美领馆行政审核过且签证页上无“clearance received”注释，同时未被美领馆拒签过。以上条件必须同时满足；<br> 2、未满14周岁的申请人（不与父母一同申请签证）或80周岁以上（含80周岁）的老人申请该签证，只要从未被美领馆拒签过即可。 <br> \n\n备注：如果您是符合中信免面谈资格，而您仍前往领事馆面谈的话，那么您有可能被拒绝进入等候大厅，或者您可能将是当天最晚一个面谈的。如果您在最近半年内申请学生签证被拒签，在您预约面谈时间时，将只能被安排在拒签的FMJ类别里。",
            "VisaManageCity": "上海",
            "Options": false,
            "OutsideNet": true,
            "Sort": 6,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 179469,
            "Name": "身份证正反面扫描件",
            "Content": "1、16周岁以上，提供正反面复印件                        <br>2、此材料用于在中信银行领取护照时提供给工作人员",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 7,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 47496,
            "Name": "当天面试材料",
            "Content": "去美领馆面试时须带以下原件：(请客人将所缺原材料全部带齐)<br>1.因私护照，英文赴美报名表, 邀请函-----由面试陪同人员带去。<br>2.彩色免冠照片两张（51mm*51mm 背景色为白色）<br>3.家庭材料：身份证，户口本，结婚证，全家福相片及去过其他国家的相片<br>4.学历证明: 毕业证书、学历证书、各种从业资格证书等<br>5.资产材料：房产证，车证，股票交割单，有价证券等<br>6.银行存款：存折或存单原件（金额人民币10万元以上，夫妻两人10万元以上）<br>7.公司材料：公司营业执照或法人证书或机构代码证（如果不能提供原件，复印件盖公章即可，法人一定要提供原件）<br>8.公司担保信：（其中个人收入请注明年薪是多少，有工资单和税单的请提供工资单和税单）<br>9.名片及公司简介<br>10.有老护照的提供老护照，公务护照如果拿不到的可提供复印件或景点照片（去过的欧洲、澳洲、美洲等发达国家的照片）<br>11.学生需提供：如果是学生身份,需提供学校抬头信笺纸打印的中英文在读证明原件，需要学校领导签字、盖章。（范例或样板可联系我们索取！）；如提供不了在读证明 请提供学生证原件；请携带成绩单和学位证明/文凭，以及银行月结单、固定存款单等资金证明。<br>12.以上要提供的每一项材料都有利于签证的签出，请尽量提供。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 123,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }]
        }, {
          "ID": 2,
          "Name": "自由职业",
          "VisaStuffs": [{
            "ID": 27111,
            "Name": "中国大陆因私护照复印件（可接收电子护照）",
            "Content": "1、护照的首页、延期页、换发页复印件；<br>\n2、行程结束后至少还有6个月有效期；<br>\n3、如若换发过护照，提供旧护整本复印件。若无或遗失，则无需提供；<br>\n4、至少留有1页空白签证页，不含备注页；<br>\n5、护照须有中文签名，学龄前儿童可由父母代签名（不可用铅笔）；<br> \n6、不接收6个月内有美国拒签记录的护照。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 1,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27110,
            "Name": "照片（1张）",
            "Content": "1、近6个月内的（5.1cmx5.1cm）白底彩照1张（照片背后用铅笔写姓名）；<br> 2、须包含整个面部，颈部和肩膀；如佩戴眼镜，不得出现反光；<br> 3、不得经过数码处理，增强效应，修版，颗粒化，压缩引起的任何可视效果。 <a href=http://pages.ctrip.com/tour/ingroup1311/074.htm target=_blank> 照片规格参考</a> ",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 2,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27109,
            "Name": "个人信息表",
            "Content": "1、填写完整并中文签名，儿童可由父母代签名；<a href=http://pages.ctrip.com/tour/visa/word/171.doc target=_blank>个人信息表 </a> <a href=http://pages.ctrip.com/tour/ingroupline_pages.asp?folder=ingroup1211&file=102 target=_blank>个人信息表填写样图 </a><br> 2、填写的联系电话需保持畅通。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 3,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27112,
            "Name": "备注",
            "Content": "当符合下列条件时，持因私护照签证申请人可选择我司美国个人旅游签证，中信银行“代传递”免面试产品。<br> 1、申请人上一次赴美签证过期时间不超过48个月，此次申请签证类型与上次相同，有过期的美国签证页所在的护照（如护照为因公护照，需包含清晰的出入境四个章），您必须在之前的签证面试时提供过十指指纹，未被美领馆行政审核过且签证页上无“clearance received”注释，同时未被美领馆拒签过。以上条件必须同时满足；<br> 2、未满14周岁的申请人（不与父母一同申请签证）或80周岁以上（含80周岁）的老人申请该签证，只要从未被美领馆拒签过即可。 <br> \n\n备注：如果您是符合中信免面谈资格，而您仍前往领事馆面谈的话，那么您有可能被拒绝进入等候大厅，或者您可能将是当天最晚一个面谈的。如果您在最近半年内申请学生签证被拒签，在您预约面谈时间时，将只能被安排在拒签的FMJ类别里。",
            "VisaManageCity": "上海",
            "Options": false,
            "OutsideNet": true,
            "Sort": 6,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 179469,
            "Name": "身份证正反面扫描件",
            "Content": "1、16周岁以上，提供正反面复印件                        <br>2、此材料用于在中信银行领取护照时提供给工作人员",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 7,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 47496,
            "Name": "当天面试材料",
            "Content": "去美领馆面试时须带以下原件：(请客人将所缺原材料全部带齐)<br>1.因私护照，英文赴美报名表, 邀请函-----由面试陪同人员带去。<br>2.彩色免冠照片两张（51mm*51mm 背景色为白色）<br>3.家庭材料：身份证，户口本，结婚证，全家福相片及去过其他国家的相片<br>4.学历证明: 毕业证书、学历证书、各种从业资格证书等<br>5.资产材料：房产证，车证，股票交割单，有价证券等<br>6.银行存款：存折或存单原件（金额人民币10万元以上，夫妻两人10万元以上）<br>7.公司材料：公司营业执照或法人证书或机构代码证（如果不能提供原件，复印件盖公章即可，法人一定要提供原件）<br>8.公司担保信：（其中个人收入请注明年薪是多少，有工资单和税单的请提供工资单和税单）<br>9.名片及公司简介<br>10.有老护照的提供老护照，公务护照如果拿不到的可提供复印件或景点照片（去过的欧洲、澳洲、美洲等发达国家的照片）<br>11.学生需提供：如果是学生身份,需提供学校抬头信笺纸打印的中英文在读证明原件，需要学校领导签字、盖章。（范例或样板可联系我们索取！）；如提供不了在读证明 请提供学生证原件；请携带成绩单和学位证明/文凭，以及银行月结单、固定存款单等资金证明。<br>12.以上要提供的每一项材料都有利于签证的签出，请尽量提供。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 123,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }]
        }, {
          "ID": 4,
          "Name": "在校学生",
          "VisaStuffs": [{
            "ID": 27111,
            "Name": "中国大陆因私护照复印件（可接收电子护照）",
            "Content": "1、护照的首页、延期页、换发页复印件；<br>\n2、行程结束后至少还有6个月有效期；<br>\n3、如若换发过护照，提供旧护整本复印件。若无或遗失，则无需提供；<br>\n4、至少留有1页空白签证页，不含备注页；<br>\n5、护照须有中文签名，学龄前儿童可由父母代签名（不可用铅笔）；<br> \n6、不接收6个月内有美国拒签记录的护照。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 1,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27110,
            "Name": "照片（1张）",
            "Content": "1、近6个月内的（5.1cmx5.1cm）白底彩照1张（照片背后用铅笔写姓名）；<br> 2、须包含整个面部，颈部和肩膀；如佩戴眼镜，不得出现反光；<br> 3、不得经过数码处理，增强效应，修版，颗粒化，压缩引起的任何可视效果。 <a href=http://pages.ctrip.com/tour/ingroup1311/074.htm target=_blank> 照片规格参考</a> ",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 2,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27109,
            "Name": "个人信息表",
            "Content": "1、填写完整并中文签名，儿童可由父母代签名；<a href=http://pages.ctrip.com/tour/visa/word/171.doc target=_blank>个人信息表 </a> <a href=http://pages.ctrip.com/tour/ingroupline_pages.asp?folder=ingroup1211&file=102 target=_blank>个人信息表填写样图 </a><br> 2、填写的联系电话需保持畅通。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 3,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27112,
            "Name": "备注",
            "Content": "当符合下列条件时，持因私护照签证申请人可选择我司美国个人旅游签证，中信银行“代传递”免面试产品。<br> 1、申请人上一次赴美签证过期时间不超过48个月，此次申请签证类型与上次相同，有过期的美国签证页所在的护照（如护照为因公护照，需包含清晰的出入境四个章），您必须在之前的签证面试时提供过十指指纹，未被美领馆行政审核过且签证页上无“clearance received”注释，同时未被美领馆拒签过。以上条件必须同时满足；<br> 2、未满14周岁的申请人（不与父母一同申请签证）或80周岁以上（含80周岁）的老人申请该签证，只要从未被美领馆拒签过即可。 <br> \n\n备注：如果您是符合中信免面谈资格，而您仍前往领事馆面谈的话，那么您有可能被拒绝进入等候大厅，或者您可能将是当天最晚一个面谈的。如果您在最近半年内申请学生签证被拒签，在您预约面谈时间时，将只能被安排在拒签的FMJ类别里。",
            "VisaManageCity": "上海",
            "Options": false,
            "OutsideNet": true,
            "Sort": 6,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 179469,
            "Name": "身份证正反面扫描件",
            "Content": "1、16周岁以上，提供正反面复印件                        <br>2、此材料用于在中信银行领取护照时提供给工作人员",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 7,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 47496,
            "Name": "当天面试材料",
            "Content": "去美领馆面试时须带以下原件：(请客人将所缺原材料全部带齐)<br>1.因私护照，英文赴美报名表, 邀请函-----由面试陪同人员带去。<br>2.彩色免冠照片两张（51mm*51mm 背景色为白色）<br>3.家庭材料：身份证，户口本，结婚证，全家福相片及去过其他国家的相片<br>4.学历证明: 毕业证书、学历证书、各种从业资格证书等<br>5.资产材料：房产证，车证，股票交割单，有价证券等<br>6.银行存款：存折或存单原件（金额人民币10万元以上，夫妻两人10万元以上）<br>7.公司材料：公司营业执照或法人证书或机构代码证（如果不能提供原件，复印件盖公章即可，法人一定要提供原件）<br>8.公司担保信：（其中个人收入请注明年薪是多少，有工资单和税单的请提供工资单和税单）<br>9.名片及公司简介<br>10.有老护照的提供老护照，公务护照如果拿不到的可提供复印件或景点照片（去过的欧洲、澳洲、美洲等发达国家的照片）<br>11.学生需提供：如果是学生身份,需提供学校抬头信笺纸打印的中英文在读证明原件，需要学校领导签字、盖章。（范例或样板可联系我们索取！）；如提供不了在读证明 请提供学生证原件；请携带成绩单和学位证明/文凭，以及银行月结单、固定存款单等资金证明。<br>12.以上要提供的每一项材料都有利于签证的签出，请尽量提供。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 123,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }]
        }, {
          "ID": 8,
          "Name": "退休",
          "VisaStuffs": [{
            "ID": 27111,
            "Name": "中国大陆因私护照复印件（可接收电子护照）",
            "Content": "1、护照的首页、延期页、换发页复印件；<br>\n2、行程结束后至少还有6个月有效期；<br>\n3、如若换发过护照，提供旧护整本复印件。若无或遗失，则无需提供；<br>\n4、至少留有1页空白签证页，不含备注页；<br>\n5、护照须有中文签名，学龄前儿童可由父母代签名（不可用铅笔）；<br> \n6、不接收6个月内有美国拒签记录的护照。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 1,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27110,
            "Name": "照片（1张）",
            "Content": "1、近6个月内的（5.1cmx5.1cm）白底彩照1张（照片背后用铅笔写姓名）；<br> 2、须包含整个面部，颈部和肩膀；如佩戴眼镜，不得出现反光；<br> 3、不得经过数码处理，增强效应，修版，颗粒化，压缩引起的任何可视效果。 <a href=http://pages.ctrip.com/tour/ingroup1311/074.htm target=_blank> 照片规格参考</a> ",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 2,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27109,
            "Name": "个人信息表",
            "Content": "1、填写完整并中文签名，儿童可由父母代签名；<a href=http://pages.ctrip.com/tour/visa/word/171.doc target=_blank>个人信息表 </a> <a href=http://pages.ctrip.com/tour/ingroupline_pages.asp?folder=ingroup1211&file=102 target=_blank>个人信息表填写样图 </a><br> 2、填写的联系电话需保持畅通。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 3,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27112,
            "Name": "备注",
            "Content": "当符合下列条件时，持因私护照签证申请人可选择我司美国个人旅游签证，中信银行“代传递”免面试产品。<br> 1、申请人上一次赴美签证过期时间不超过48个月，此次申请签证类型与上次相同，有过期的美国签证页所在的护照（如护照为因公护照，需包含清晰的出入境四个章），您必须在之前的签证面试时提供过十指指纹，未被美领馆行政审核过且签证页上无“clearance received”注释，同时未被美领馆拒签过。以上条件必须同时满足；<br> 2、未满14周岁的申请人（不与父母一同申请签证）或80周岁以上（含80周岁）的老人申请该签证，只要从未被美领馆拒签过即可。 <br> \n\n备注：如果您是符合中信免面谈资格，而您仍前往领事馆面谈的话，那么您有可能被拒绝进入等候大厅，或者您可能将是当天最晚一个面谈的。如果您在最近半年内申请学生签证被拒签，在您预约面谈时间时，将只能被安排在拒签的FMJ类别里。",
            "VisaManageCity": "上海",
            "Options": false,
            "OutsideNet": true,
            "Sort": 6,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 179469,
            "Name": "身份证正反面扫描件",
            "Content": "1、16周岁以上，提供正反面复印件                        <br>2、此材料用于在中信银行领取护照时提供给工作人员",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 7,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 47496,
            "Name": "当天面试材料",
            "Content": "去美领馆面试时须带以下原件：(请客人将所缺原材料全部带齐)<br>1.因私护照，英文赴美报名表, 邀请函-----由面试陪同人员带去。<br>2.彩色免冠照片两张（51mm*51mm 背景色为白色）<br>3.家庭材料：身份证，户口本，结婚证，全家福相片及去过其他国家的相片<br>4.学历证明: 毕业证书、学历证书、各种从业资格证书等<br>5.资产材料：房产证，车证，股票交割单，有价证券等<br>6.银行存款：存折或存单原件（金额人民币10万元以上，夫妻两人10万元以上）<br>7.公司材料：公司营业执照或法人证书或机构代码证（如果不能提供原件，复印件盖公章即可，法人一定要提供原件）<br>8.公司担保信：（其中个人收入请注明年薪是多少，有工资单和税单的请提供工资单和税单）<br>9.名片及公司简介<br>10.有老护照的提供老护照，公务护照如果拿不到的可提供复印件或景点照片（去过的欧洲、澳洲、美洲等发达国家的照片）<br>11.学生需提供：如果是学生身份,需提供学校抬头信笺纸打印的中英文在读证明原件，需要学校领导签字、盖章。（范例或样板可联系我们索取！）；如提供不了在读证明 请提供学生证原件；请携带成绩单和学位证明/文凭，以及银行月结单、固定存款单等资金证明。<br>12.以上要提供的每一项材料都有利于签证的签出，请尽量提供。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 123,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }]
        }, {
          "ID": 16,
          "Name": "学龄前儿童",
          "VisaStuffs": [{
            "ID": 27111,
            "Name": "中国大陆因私护照复印件（可接收电子护照）",
            "Content": "1、护照的首页、延期页、换发页复印件；<br>\n2、行程结束后至少还有6个月有效期；<br>\n3、如若换发过护照，提供旧护整本复印件。若无或遗失，则无需提供；<br>\n4、至少留有1页空白签证页，不含备注页；<br>\n5、护照须有中文签名，学龄前儿童可由父母代签名（不可用铅笔）；<br> \n6、不接收6个月内有美国拒签记录的护照。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 1,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27110,
            "Name": "照片（1张）",
            "Content": "1、近6个月内的（5.1cmx5.1cm）白底彩照1张（照片背后用铅笔写姓名）；<br> 2、须包含整个面部，颈部和肩膀；如佩戴眼镜，不得出现反光；<br> 3、不得经过数码处理，增强效应，修版，颗粒化，压缩引起的任何可视效果。 <a href=http://pages.ctrip.com/tour/ingroup1311/074.htm target=_blank> 照片规格参考</a> ",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 2,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27109,
            "Name": "个人信息表",
            "Content": "1、填写完整并中文签名，儿童可由父母代签名；<a href=http://pages.ctrip.com/tour/visa/word/171.doc target=_blank>个人信息表 </a> <a href=http://pages.ctrip.com/tour/ingroupline_pages.asp?folder=ingroup1211&file=102 target=_blank>个人信息表填写样图 </a><br> 2、填写的联系电话需保持畅通。",
            "VisaManageCity": "上海",
            "Options": true,
            "OutsideNet": true,
            "Sort": 3,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }, {
            "ID": 27112,
            "Name": "备注",
            "Content": "当符合下列条件时，持因私护照签证申请人可选择我司美国个人旅游签证，中信银行“代传递”免面试产品。<br> 1、申请人上一次赴美签证过期时间不超过48个月，此次申请签证类型与上次相同，有过期的美国签证页所在的护照（如护照为因公护照，需包含清晰的出入境四个章），您必须在之前的签证面试时提供过十指指纹，未被美领馆行政审核过且签证页上无“clearance received”注释，同时未被美领馆拒签过。以上条件必须同时满足；<br> 2、未满14周岁的申请人（不与父母一同申请签证）或80周岁以上（含80周岁）的老人申请该签证，只要从未被美领馆拒签过即可。 <br> \n\n备注：如果您是符合中信免面谈资格，而您仍前往领事馆面谈的话，那么您有可能被拒绝进入等候大厅，或者您可能将是当天最晚一个面谈的。如果您在最近半年内申请学生签证被拒签，在您预约面谈时间时，将只能被安排在拒签的FMJ类别里。",
            "VisaManageCity": "上海",
            "Options": false,
            "OutsideNet": true,
            "Sort": 6,
            "VisaAcceptability": null,
            "VisaUnAcceptability": null
          }]
        }]
      }]
    },
    "OrderingNeedToKnowInfo": {
      "CorpDescInfo": "(本产品由北京携程国际旅行社有限公司代理招徕，委托社为北京达美国际旅行社有限责任公司，具体的旅游服务和操作由委托社提供。<a title=\"网上预订须知\" rel=\"nofollow\" href=\"/bookingnext/Knowledge?Type=NeedKnow&SalesCity=1&PKG=6673978\" target='_blank'>网上预订须知</a>)",
      "PayInfos": [{
        "Type": "支付信息",
        "Desc": "本产品支持信用卡、网银/第三方、礼品卡、储蓄卡、微信支付，具体以支付页为准。本产品为特例产品，不支持使用旅游度假优惠券预订。"
      }],
      "SafetyGuide": "1.携程从出行常识、旅游活动和特殊人群三方面为您提供旅游安全指南，请在出行前仔细阅读。<a rel=\"nofollow\" href=\"http://pages.ctrip.com/commerce/promote/201004/package/dj/page_5.htm\" target=\"_blank\">查看详情</a>",
      "OrderingNeedToKnowInfoDetails": [{
        "TitleName": "预订限制",
        "Details": [{
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "预订限制",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "本产品不接受21周岁以下(含)的客人单独报名出游，敬请谅解！",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "预订限制",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "此产品报价是按照2成人入住1间房计算的价格。如您的订单产生单房，请在后续附加项目页面中选择单房差可选项。如您3-4人同行，且愿意多人同住（不加床）的，可在后续附加项目页面中选择多人立减可选项，无需再选择单房差。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "预订限制",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "年龄3--12周岁（不含）,不占床,服务标准同成人",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }]
      }, {
        "TitleName": "预订说明",
        "Details": [{
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "预订说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "请您在预订时务必提供准确、完整的信息（姓名、性别、证件号码、国籍、联系方式、是否成人或儿童等），以免产生预订错误，影响出行。如因客人提供错误个人信息而造成损失，我社不承担任何责任。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "预订说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "联运段航班因航空公司政策限制，不可指定航班，需要向航空公司现询。联运航班可能会提前（或延后）1-2天，如联运航班提前（或延后），需客人自行解决住宿问题。如果无法乘坐我司安排的联运段航班，请客人自行前往中转城市，费用自理。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "预订说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "如果联运段航班已经出票，但因客人原因导致无法乘坐第一段航班，按航空公司规则，后面几段航班默认放弃乘坐，由此产生的损失，由客人自行承担。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }]
      }, {
        "TitleName": "产品说明",
        "Details": [{
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "产品说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "最低成团人数2人，宣布成团前，旅游者和出境社取消订单，双方互不承担违约责任；宣布成团后，旅游者和出境社取消订单，按照双方合同约定各自承担违约责任。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "产品说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "最终的航班信息请以出团说明会或出团通知书为准。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "产品说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "如因意外事件及不可抗力，包括但不限于，航空公司运力调配、航权审核、机场临时关闭、天气原因、航空管制等，导致航班取消或延期的，旅行社将尽最大努力协助您办理变更事宜，如产生差价，多退少补。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "产品说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "具体航班号及航班时刻，请以最终所出机票信息为准。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "产品说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "本行程为我社委托当地旅行社散客拼团线路，在保证承诺的服务内容和标准不变的前提下，会与其他旅行社的客人拼成一个团，统一安排行程。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "产品说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "出游过程中，如遇不可抗力因素造成景点未能正常游玩，导游经与客人协商后可根据实际情况取消或更换该景点，或由导游在现场按旅游产品中的门票价退还费用，退费不以景区挂牌价为准，敬请谅解。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "产品说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "行程中的赠送项目，如因交通、天气等不可抗因素导致不能赠送的、或因您个人原因不能参观的，费用不退，敬请谅解。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "产品说明",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "本产品全程不提供领队服务，在旅游目的地由当地导游提供相关服务。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }]
      }, {
        "TitleName": "违约条款",
        "Details": [{
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "违约条款",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "旅行社违约：<br />行程前30日至15日，退还全额旅游费用，支付旅游费用总额2％的违约金。<br />行程前14日至7日，退还全额旅游费用，支付旅游费用总额5％的违约金。<br />行程前6日至4日，退还全额旅游费用，支付旅游费用总额10％的违约金。<br />行程前3日至1日，退还全额旅游费用，支付旅游费用总额15％的违约金。<br />行程开始当日，退还全额旅游费用，支付旅游费用总额20％的违约金。<br />",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "违约条款",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "旅游者违约：<br />在行程前解除合同的，机（车、船）票费用按实结算后，其余必要的费用扣除标准为：<br />行程前30日至15日，收取旅游费用总额5％的违约金。<br />行程前14日至7日，收取旅游费用总额10％的违约金。<br />行程前6日至4日，收取旅游费用总额15％的违约金。<br />行程前3日至1日，收取旅游费用总额25％的违约金。<br />行程开始当日，收取旅游费用总额30％的违约金。<br />",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }]
      }, {
        "TitleName": "出行须知",
        "Details": [{
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "出行须知",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "我司将在出行前7天向您发送《出团通知书》或导游的确认电话，如未收到请及时联系携程工作人员。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "出行须知",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "请在导游约定的时间到达上车地点集合，切勿迟到，以免耽误其他游客行程。若因迟到导致无法随车游览，责任自负，敬请谅解。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "出行须知",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "为了不耽误您的行程，请您在国际航班起飞前180分钟到达机场办理登机＆出入境相关手续，如涉及海外国内段行程，请您在航班起飞前120分钟达到机场办理登机手续。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "出行须知",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "该目的地为小费制国家，接受各种服务一般都要支付小费。建议按照国际惯例，由客人自愿支付服务人员小费（8*天数/美元/人）以资鼓励。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "出行须知",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "请您严格遵守境外旅游目的地有关国家法律法规，切勿从事象牙等濒危野生动植物及其制品交易或携带相关物品，避免因触犯法律损害自身利益。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "出行须知",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "根据最新发布的《中华人民共和国禁止携带、邮寄进境的动植物及其产品和其他检疫物名录》，将燕窝、新鲜水果、蔬菜、动物源性中药材、转基因生物材料等列入严禁携带或邮寄进境项目，敬请知晓。更多信息，<a target=_blank href=http://dzwjyjgs.aqsiq.gov.cn/rdgz/201202/t20120223_209369.htm>请点击</a>。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "出行须知",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "根据中国海关总署颁布的2010年54号令，进境公民旅客携带在境外获取的个人自用进境物品总值在5000元以内（含5000元）的，海关予以免税放行。烟草制品、酒精制品、照相机、摄像机等20种商品不在免税范围内，敬请知晓。<a href=http://www.customs.gov.cn/publish/portal0/tab3889/module1188/info236878.htm target=_blank>点击详情。</a>",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "出行须知",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "为确保锂电池的安全运输，避免发生不安全事件，我们友情提醒您，民航局将对旅客携带锂电池乘机进行严格检查。详情请参考<a target=_blank href=http://pages.ctrip.com/tour/ingroupline_pages.asp?folder=ingroup0808&file=0223>民航局关于旅客携带锂电池乘机的规定</a>。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }, {
          "Pkg": 6673978,
          "Sequence": 0,
          "MainTitle": "预订须知",
          "SubTitle": "出行须知",
          "Symbol": null,
          "DetailSequence": 0,
          "Detail": "请务必仔细阅读<a target=_blank href=http://vacations.ctrip.com/notes/670.html>《国际航班手提行李规定》</a>。",
          "Style": null,
          "Color": "",
          "ClauseTypeName": null
        }]
      }],
      "Activities": null
    },
    "Activities": null,
    "ChildPriceStandardInfo": {
      "Ages": [3, 12],
      "Height": null,
      "Title": "3-12周岁（不含）",
      "Content": "儿童价标准：年龄3-12周岁（不含），不占床，服务标准同成人"
    },
    "PromotionInfo": {
      "Promotions": [],
      "PromotionTags": ["特卖汇"]
    }
  },
  "errno": 0,
  "errmsg": "OK"
}