module.exports = {
    "errmsg": "OK",
    "errno": 0,
    "data": {
        "CustomerInfoItems": [{
            "CustomerInfoItemID": 1,
            "CustomerInfoItemModel": 1,
            "CustomerInfoItemType": "ChineseName",
            "Name": "中文姓名",
            "RegEx": "",
            "Note": null,
            "SortNumber": 1,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 2,
            "CustomerInfoItemModel": 1,
            "CustomerInfoItemType": "EnglishName",
            "Name": "英文姓名",
            "RegEx": "",
            "Note": null,
            "SortNumber": 2,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 4,
            "CustomerInfoItemModel": 1,
            "CustomerInfoItemType": "Nationality",
            "Name": "国籍",
            "RegEx": "",
            "Note": null,
            "SortNumber": 4,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 5,
            "CustomerInfoItemModel": 1,
            "CustomerInfoItemType": "IDType",
            "Name": "证件类型",
            "RegEx": "",
            "Note": null,
            "SortNumber": 5,
            "IsRequired": false
        }, {
            "CustomerInfoItemID": 6,
            "CustomerInfoItemModel": 1,
            "CustomerInfoItemType": "Sex",
            "Name": "性别",
            "RegEx": "",
            "Note": null,
            "SortNumber": 6,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 7,
            "CustomerInfoItemModel": 1,
            "CustomerInfoItemType": "IDNumber",
            "Name": "证件号",
            "RegEx": "",
            "Note": null,
            "SortNumber": 7,
            "IsRequired": false
        }, {
            "CustomerInfoItemID": 8,
            "CustomerInfoItemModel": 1,
            "CustomerInfoItemType": "Birthday",
            "Name": "出生日期",
            "RegEx": "",
            "Note": null,
            "SortNumber": 8,
            "IsRequired": false
        }, {
            "CustomerInfoItemID": 10,
            "CustomerInfoItemModel": 1,
            "CustomerInfoItemType": "CardValidUntil",
            "Name": "证件有效期",
            "RegEx": "",
            "Note": null,
            "SortNumber": 10,
            "IsRequired": false
        }, {
            "CustomerInfoItemID": 11,
            "CustomerInfoItemModel": 1,
            "CustomerInfoItemType": "ContactPhone",
            "Name": "联系电话",
            "RegEx": "",
            "Note": null,
            "SortNumber": 11,
            "IsRequired": false
        }, {
            "CustomerInfoItemID": 13,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "1",
            "Name": "身份证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 13,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 15,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "3",
            "Name": "学生证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 15,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 16,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "4",
            "Name": "军官证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 16,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 17,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "6",
            "Name": "驾驶证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 17,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 18,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "7",
            "Name": "回乡证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 18,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 19,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "8",
            "Name": "台胞证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 19,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 20,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "10",
            "Name": "港澳通行证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 20,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 21,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "11",
            "Name": "国际海员证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 21,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 22,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "20",
            "Name": "外国人永久居留证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 22,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 23,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "21",
            "Name": "旅行证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 23,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 24,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "22",
            "Name": "台湾通行证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 24,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 25,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "23",
            "Name": "士兵证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 25,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 26,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "24",
            "Name": "临时身份证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 26,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 27,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "25",
            "Name": "户口簿",
            "RegEx": "",
            "Note": null,
            "SortNumber": 27,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 28,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "26",
            "Name": "警官证",
            "RegEx": "",
            "Note": null,
            "SortNumber": 28,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 29,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "99",
            "Name": "其它",
            "RegEx": "",
            "Note": null,
            "SortNumber": 29,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 30,
            "CustomerInfoItemModel": 2,
            "CustomerInfoItemType": "100",
            "Name": "稍后提供",
            "RegEx": "",
            "Note": null,
            "SortNumber": 30,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 60,
            "CustomerInfoItemModel": 1,
            "CustomerInfoItemType": "CustomerType",
            "Name": "客户类别",
            "RegEx": "",
            "Note": null,
            "SortNumber": 31,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 61,
            "CustomerInfoItemModel": 3,
            "CustomerInfoItemType": "Officer_1",
            "Name": "在职",
            "RegEx": "",
            "Note": null,
            "SortNumber": 32,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 62,
            "CustomerInfoItemModel": 3,
            "CustomerInfoItemType": "Freelance_1",
            "Name": "自由职业",
            "RegEx": "",
            "Note": null,
            "SortNumber": 33,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 63,
            "CustomerInfoItemModel": 3,
            "CustomerInfoItemType": "Students_1",
            "Name": "在校学生",
            "RegEx": "",
            "Note": null,
            "SortNumber": 34,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 64,
            "CustomerInfoItemModel": 3,
            "CustomerInfoItemType": "Retirement_1",
            "Name": "退休",
            "RegEx": "",
            "Note": null,
            "SortNumber": 35,
            "IsRequired": true
        }, {
            "CustomerInfoItemID": 65,
            "CustomerInfoItemModel": 3,
            "CustomerInfoItemType": "Preschoolers_1",
            "Name": "学龄前儿童",
            "RegEx": "",
            "Note": null,
            "SortNumber": 36,
            "IsRequired": true
        }],
        "FillInNumberLimit": "A",
        "IsVisaBySelf": false
    }
}