module.exports = {
    "errmsg": "OK",
    "errno": 0,
    "data": {
        "CustomerInfoTemplate": {
            "CustomerInfoItems": [{
                "CustomerInfoItemID": 20,
                "CustomerInfoItemModel": 2,
                "CustomerInfoItemType": "10",
                "Name": "港澳通行证",
                "RegEx": "",
                "Note": null,
                "SortNumber": 0,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 1,
                "CustomerInfoItemModel": 1,
                "CustomerInfoItemType": "ChineseName",
                "Name": "中文姓名",
                "RegEx": "",
                "Note": null,
                "SortNumber": 1,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 2,
                "CustomerInfoItemModel": 1,
                "CustomerInfoItemType": "EnglishName",
                "Name": "英文姓名",
                "RegEx": "",
                "Note": null,
                "SortNumber": 2,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 4,
                "CustomerInfoItemModel": 1,
                "CustomerInfoItemType": "Nationality",
                "Name": "国籍",
                "RegEx": "",
                "Note": null,
                "SortNumber": 4,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 5,
                "CustomerInfoItemModel": 1,
                "CustomerInfoItemType": "IDType",
                "Name": "证件类型",
                "RegEx": "",
                "Note": null,
                "SortNumber": 5,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 6,
                "CustomerInfoItemModel": 1,
                "CustomerInfoItemType": "Sex",
                "Name": "性别",
                "RegEx": "",
                "Note": null,
                "SortNumber": 6,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 7,
                "CustomerInfoItemModel": 1,
                "CustomerInfoItemType": "IDNumber",
                "Name": "证件号",
                "RegEx": "",
                "Note": null,
                "SortNumber": 7,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 8,
                "CustomerInfoItemModel": 1,
                "CustomerInfoItemType": "Birthday",
                "Name": "出生日期",
                "RegEx": "",
                "Note": null,
                "SortNumber": 8,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 11,
                "CustomerInfoItemModel": 1,
                "CustomerInfoItemType": "ContactPhone",
                "Name": "联系电话",
                "RegEx": "",
                "Note": null,
                "SortNumber": 11,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 14,
                "CustomerInfoItemModel": 2,
                "CustomerInfoItemType": "2",
                "Name": "护照",
                "RegEx": "",
                "Note": null,
                "SortNumber": 14,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 18,
                "CustomerInfoItemModel": 2,
                "CustomerInfoItemType": "7",
                "Name": "回乡证",
                "RegEx": "",
                "Note": null,
                "SortNumber": 18,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 19,
                "CustomerInfoItemModel": 2,
                "CustomerInfoItemType": "8",
                "Name": "台胞证",
                "RegEx": "",
                "Note": null,
                "SortNumber": 19,
                "IsRequired": true
            }, {
                "CustomerInfoItemID": 40,
                "CustomerInfoItemModel": 1,
                "CustomerInfoItemType": "CustomerType",
                "Name": "客户类别",
                "RegEx": "",
                "Note": null,
                "SortNumber": 31,
                "IsRequired": true
            }],
            "FillInNumberLimit": "A",
            "IsVisaBySelf": false,
            "VisaTypeInfo": {
                "Tips": null,
                "VisaTypeItems": null
            }
        },
        "Invoice": {
            "Content": [{
                "Key": 1,
                "Value": "旅游服务费"
            }, {
                "Key": 4,
                "Value": "签证费"
            }, {
                "Key": 8,
                "Value": "机票＋酒店"
            }, {
                "Key": 512,
                "Value": "台湾团队旅游费"
            }, {
                "Key": 1024,
                "Value": "服务费"
            }],
            "MyInvoices": [{
                "Key": 10149060,
                "Value": "11111"
            }, {
                "Key": 10068306,
                "Value": "sdfs"
            }, {
                "Key": 10041167,
                "Value": "gstt1"
            }, {
                "Key": 10012248,
                "Value": "啊紧身裤"
            }, {
                "Key": 10011131,
                "Value": "发票抬头"
            }, {
                "Key": 9759992,
                "Value": "大法师"
            }, {
                "Key": 8742845,
                "Value": "车子"
            }, {
                "Key": 8704513,
                "Value": "待定"
            }, {
                "Key": 8413792,
                "Value": "nsfocus"
            }, {
                "Key": 8388785,
                "Value": "发个广告广告"
            }, {
                "Key": 8176632,
                "Value": "体育用品"
            }, {
                "Key": 7903930,
                "Value": "测试结果"
            }, {
                "Key": 6696555,
                "Value": "份额公司"
            }, {
                "Key": 6403676,
                "Value": "fgfgh"
            }, {
                "Key": 6403669,
                "Value": "啊萨大声的"
            }, {
                "Key": 6028197,
                "Value": "携程旅行网"
            }, {
                "Key": 5799410,
                "Value": "test"
            }, {
                "Key": 5378992,
                "Value": "asd"
            }, {
                "Key": 5760620,
                "Value": "测试"
            }, {
                "Key": 3008181,
                "Value": "携程计算机技术（上海）"
            }, {
                "Key": 5650696,
                "Value": "asdf"
            }, {
                "Key": 5298452,
                "Value": "xxxxxxx"
            }, {
                "Key": 2951053,
                "Value": "测试抬头"
            }, {
                "Key": 1820917,
                "Value": "陈一新"
            }, {
                "Key": 1337740,
                "Value": "上海浦东科技馆2"
            }, {
                "Key": 603410,
                "Value": "上海携程国际旅行社有限公司"
            }],
            "InvoiceDesc": "您的发票将于返程后5个工作日内开具并邮寄给您，请注意查收。",
            "IsSupportEinvoice": false
        },
        "DeliveryReult": {
            "SelfPickupAddress": ["上海市长宁区福泉路99号携程网络技术大楼 邮编：200335"],
            "CityCanton": [{
                "Key": 17,
                "Value": "长宁区"
            }, {
                "Key": 18,
                "Value": "普陀区"
            }, {
                "Key": 19,
                "Value": "杨浦区"
            }, {
                "Key": 20,
                "Value": "闸北区"
            }, {
                "Key": 21,
                "Value": "虹口区"
            }, {
                "Key": 22,
                "Value": "徐汇区"
            }, {
                "Key": 23,
                "Value": "静安区"
            }, {
                "Key": 24,
                "Value": "卢湾区"
            }, {
                "Key": 25,
                "Value": "黄浦区"
            }, {
                "Key": 26,
                "Value": "闵行区"
            }, {
                "Key": 27,
                "Value": "嘉定区"
            }, {
                "Key": 28,
                "Value": "宝山区"
            }, {
                "Key": 29,
                "Value": "松江区"
            }, {
                "Key": 30,
                "Value": "浦东新区"
            }, {
                "Key": 31,
                "Value": "南汇区（暂未开通）"
            }, {
                "Key": 32,
                "Value": "奉贤区（暂未开通）"
            }, {
                "Key": 33,
                "Value": "青浦区"
            }, {
                "Key": 34,
                "Value": "金山区"
            }, {
                "Key": 35,
                "Value": "崇明县（暂未开通）"
            }],
            "DeliveryInfoList": [{
                "isHasInvoice": 1,
                "DeliveryGoodsDescriptions": ["发票"],
                "DeliveryType": [{
                    "DeliveryAmount": 10,
                    "DeliveryType": 3,
                    "IsSupportIntegralDelivery": false,
                    "IntegralDeliverAmount": 0
                }]
            }],
            "MyEMSAddress": [{
                "InfoId": 42630450,
                "Address": "南京西路1000号",
                "ProvinceId": 2,
                "ProvinceName": "上海",
                "CityId": 2,
                "CityName": "上海市",
                "CantonID": 112,
                "CantonName": "静安区",
                "Post": "200333",
                "Recipient": "test",
                "Tel": "13000010003",
                "Mobile": ""
            }],
            "InCityDelivery": [{
                "InfoId": 42630450,
                "Address": "南京西路1000号",
                "ProvinceId": 0,
                "ProvinceName": null,
                "CityId": 2,
                "CityName": "上海市",
                "CantonID": 112,
                "CantonName": "静安区",
                "Post": null,
                "Recipient": null,
                "Tel": null,
                "Mobile": null
            }],
            "CityName": "上海"
        },
        "PickUpInfos": [],
        "Reminder": null,
        "OrderPassengerList": null,
        "OrderDelivery": null,
        "OrderInvoice": null,
        "OrderOther": null,
        "IsVisa": false
    }
}